```{r}
library(rvest)
library(stringr)
library(dplyr)
library(igraph)
library(tidygraph)
library(tidyverse)
library(ggraph)

# Define the common part of the URL
common_url <- "https://www.imdb.com/list/ls006266261/?sort=list_order,asc&st_dt=&mode=detail&page="

# Extract the numbers from the common part of the URL
numbers <- 1:10

# Generate the complete URLs by joining the common part with the numbers
urls <- str_c(common_url, numbers)

# Initialize empty lists to store all titles, actors, directors, ratings, and profits
all_titles <- c()
all_actors <- c()
all_directors <- c()
all_ratings <- c()
all_profits <- c()

# Loop through each URL
for (url in urls) {
  # Read HTML content of the webpage
  webpage <- read_html(url)
  
  # Find titles, actors, directors, ratings, and profits based on CSS selectors
  titles <- webpage %>% html_nodes(".lister-item-index+ a")
  actors <- webpage %>% html_nodes(".ghost~ a , .mode-detail:nth-child(17) .text-small a")
  directors <- webpage %>% html_nodes(".text-muted a:nth-child(1)")
  ratings <- webpage %>% html_nodes(".ipl-rating-star.small .ipl-rating-star__rating")
  profits <- webpage %>% html_nodes(".ghost~ .text-muted+ span")
  
  # Extract text content of the nodes
  titles_text <- titles %>% html_text()
  actors_text <- actors %>% html_text()
  directors_text <- directors %>% html_text()
  ratings_text <- ratings %>% html_text()
  profits_text <- profits %>% html_text()
  
  # Append titles, actors, directors, ratings, and profits to the vectors
  all_titles <- c(all_titles, titles_text)
  all_actors <- c(all_actors, actors_text)
  all_directors <- c(all_directors, directors_text)
  all_ratings <- c(all_ratings, ratings_text)
  all_profits <- c(all_profits, profits_text)
}

# Remove actors number 65 and 66 from the list of actors
all_actors <- all_actors[-c(65, 66, 867, 1268, 1669, 2070, 2471, 3272, 3673)]

#all_profits <- all_profits[-c(1, 2, 102, 103, 201, 202)] #, 294, 295, 390, 391, 480, 481, 577, 578, 671, 672, 761, 762, 859, 860)]
# Find indices of elements containing "|"
indices <- grep("\\|", all_profits)

# Remove elements containing "|"
all_profits <- all_profits[-indices]

# Positions to insert "N/A"
positions <- c(45,109, 149, 167, 174, 176, 222, 235, 236, 246, 250, 327, 334, 347, 378, 380, 397, 403, 405, 409, 423, 429, 438, 443, 451, 460, 466, 473, 494, 518, 556, 569, 588, 597, 601, 607, 610, 646, 657, 674, 680, 687, 732, 740, 757, 759, 767, 776, 778, 779, 790, 793, 794, 797, 802, 867, 874, 886, 908, 916, 946, 948, 980, 987, 992)

# Iterate over each position and insert "N/A"
for (pos in positions) {
  all_profits <- c(all_profits[1:(pos-1)], "N/A", all_profits[pos:length(all_profits)])
}
# Calculate the number of iterations based on the length of all_actors
iterations <- length(all_actors) %/% 4

# Initialize empty lists to store combined data
combined_list <- vector("list", iterations)

# Iterate through the lists
for (i in 1:iterations) {
  start_idx <- (i - 1) * 4 + 1
  end_idx <- i * 4
  combined_list[[i]] <- list(
    Title = all_titles[i],
    Actor1 = all_actors[start_idx],
    Actor2 = all_actors[start_idx + 1],
    Actor3 = all_actors[start_idx + 2],
    Actor4 = all_actors[start_idx + 3],
    Director = all_directors[i],
    Rating = all_ratings[i],
    Profit = all_profits[i]
  )
}

# Convert the list to a data frame
df <- do.call(rbind, combined_list)
# Convert the list to a data frame
df <- as.data.frame(do.call(rbind, combined_list))

# Print the resulting data frame
View(df)

# Assuming your data frame is called df
as.numeric(df$Rating)
subset_df <- subset(df, Rating > 8.6)
View(subset_df)


#changes rating from char to num
as.numeric(df$Rating)


#Create a df that has movies with ratings 8.6 and higher
Rating_df <- subset(df, Rating >= 8.6, c("Title", "Actor1", "Actor2", "Actor3", "Actor4"))

view(Rating_df)

#Create a df that has certain directors movies
Director_df <- subset(df, Director == "Steven Spielberg", c("Title", "Actor1", "Actor2", "Actor3", "Actor4"))

view(Director_df)

# Reshape the data frame
Director_df_long <- pivot_longer(Director_df, cols = starts_with("Actor"), values_to = "Actor")

# Remove "Actor" from the names of the 'Actor' column
Director_df_long$Actor <- gsub("Actor", "", Director_df_long$Actor)

# Remove the 'name' column
Director_df_long <- select(Director_df_long, -name)

# Order the data frame by Title
Director_df_long <- arrange(Director_df_long, Title)

# View the resulting data frame
View(Director_df_long)


# Switch the columns
switched_director_df_long <- Director_df_long[, c("Actor", "Title")]

# Print the first few rows of the switched data frame to verify the changes
View(switched_director_df_long)


network <- switched_director_df_long %>% 
  as_tbl_graph()
network

class(network)

network %>% 
  activate(nodes) %>%
  mutate(degree = centrality_degree()) %>%
  as_tibble() %>%
  arrange(desc(degree))

library(visNetwork)

vis_network <- network %>% 
  mutate(group = if_else(condition = name %in% unique(switched_director_df_long$Actor),
                         true = "Actor",
                         false = "Title")) %>%
  toVisNetworkData()

visNetwork(nodes=vis_network$nodes, edges = vis_network$edges,
           width = "100%", height = "600px",
           main = "Bacon Number") %>%
  visLayout(randomSeed = 1000) %>%
  addFontAwesome() %>%
  visGroups(groupname = "Title", shape = "icon",
            icon = list(code = "f008", color = "darkblue")) %>%
  visGroups(groupname = "Character", shape = "icon",
           icon = list(code = "f007", color ="red")) %>%
  visOptions(highlightNearest = list(enabled = TRUE, hover = TRUE),
             nodesIdSelection = TRUE) %>%
  visInteraction(navigationButtons = TRUE)

```
```{r}

Graph_Director = function(director)
{
  Director_df <- subset(df, Director == director, c("Title", "Actor1", "Actor2", "Actor3", "Actor4"))
  # Reshape the data frame
Director_df_long <- pivot_longer(Director_df, cols = starts_with("Actor"), values_to = "Actor")

# Remove "Actor" from the names of the 'Actor' column
Director_df_long$Actor <- gsub("Actor", "", Director_df_long$Actor)

# Remove the 'name' column
Director_df_long <- select(Director_df_long, -name)

# Order the data frame by Title
Director_df_long <- arrange(Director_df_long, Title)

# View the resulting data frame
View(Director_df_long)
  

# Switch the columns
switched_director_df_long <- Director_df_long[, c("Actor", "Title")]

# Print the first few rows of the switched data frame to verify the changes
View(switched_director_df_long)


network <- switched_director_df_long %>% 
  as_tbl_graph()
network

class(network)

network %>% 
  activate(nodes) %>%
  mutate(degree = centrality_degree()) %>%
  as_tibble() %>%
  arrange(desc(degree))

library(visNetwork)

vis_network <- network %>% 
  mutate(group = if_else(condition = name %in% unique(switched_director_df_long$Actor),
                         true = "Actor",
                         false = "Title")) %>%
  toVisNetworkData()

visNetwork(nodes=vis_network$nodes, edges = vis_network$edges,
           width = "100%", height = "600px",
           main = "Bacon Number") %>%
  visLayout(randomSeed = 1000) %>%
  addFontAwesome() %>%
  visGroups(groupname = "Title", shape = "icon",
            icon = list(code = "f008", color = "darkblue")) %>%
  visGroups(groupname = "Character", shape = "icon",
           icon = list(code = "f007", color ="red")) %>%
  visOptions(highlightNearest = list(enabled = TRUE, hover = TRUE),
             nodesIdSelection = TRUE) %>%
  visInteraction(navigationButtons = TRUE)
  
  
  
  
  
  
}
  




Graph_Director(all_directors[1:10])










```






```{r}
df_long <- pivot_longer(df, cols = starts_with("Actor"), values_to = "Actor")
df_long$Actor <- gsub("Actor", "", df_long$Actor)
df_long <- select(df_long, -name)
df_long <- arrange(df_long, Title)
df_long <- df_long %>% select(Actor, Title)



library(igraph)

# Create a graph object
graph <- graph.data.frame(df_long, directed = FALSE)

# Find the index of Tom Hanks in the graph
tom_hanks_index <- which(V(graph)$name == "Tom Hanks")

# Calculate shortest paths to Tom Hanks for all actors
hanks_numbers <- shortest.paths(graph, to = tom_hanks_index)

# Extract Hanks numbers for each actor
actors <- V(graph)$name
hanks_numbers_df <- data.frame(actor = actors, hanks_number = hanks_numbers / 2)

# Filter out movies from the list of "Hanks Numbers"
filtered_hanks_numbers_df <- hanks_numbers_df[!hanks_numbers_df$actor %in% all_titles, ]

# Remove actors that aren't connected to Tom Hanks
filtered_hanks_numbers_df <-  filtered_hanks_numbers_df[filtered_hanks_numbers_df$Tom.Hanks != "Inf", ]
# Remove the column labeled "actor"
filtered_hanks_numbers_df <- select(filtered_hanks_numbers_df, -actor)
library(dplyr)

# Arrange the results in descending order based on the "hanks_number" column
filtered_hanks_numbers_df <- arrange(filtered_hanks_numbers_df, desc(Tom.Hanks))

View(filtered_hanks_numbers_df)
print(filtered_hanks_numbers_df)
find_hanks_number = function(actor)
{
 x = filtered_hanks_numbers_df[actor,2]
 if(is.na(x))
 {
   return("They are unconnected in our data or you may need to check spelling")
 }
 else
 {
   return(x)
 }
}

find_hanks_number("Uma Thurman")

# Create histogram
histogram <- ggplot(filtered_hanks_numbers_df, aes(x = Tom.Hanks)) +
  geom_histogram(binwidth = 1, fill = "skyblue", color = "black", alpha = 0.7) +  # Adjust binwidth as needed
  labs(title = "Histogram of Hanks Numbers",
       x = "Hanks Number",
       y = "Frequency") +
  theme_minimal()

# Calculate mean value
mean_value <- mean(filtered_hanks_numbers_df$Tom.Hanks)

# Add mean line
histogram <- histogram + geom_vline(xintercept = mean_value, color = "red", linetype = "dashed")

# Summary of the data
summary(filtered_hanks_numbers_df)

# Print histogram
print(histogram)

```
